databases:
  - name: rra
    databaseName: rra
    user: rra_user

services:
  - type: web
    name: rracm
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rra
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false